version: 2
updates:

  # Maintain dependencies for npm.
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
    versioning-strategy: increase
    rebase-strategy: disabled

  # Maintain dependencies for Composer.
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - dependencies
    versioning-strategy: increase-if-necessary
    rebase-strategy: disabled
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
