language: php
dist: trusty
sudo: false

git:
  depth: 5

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

env:
  matrix:
    - dependencies=lowest
    - dependencies=highest

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_install:
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

install:
  - if [ -z "$dependencies" ];          then composer install                  --no-progress --no-scripts --no-suggest -n; fi;
  - if [ "$dependencies" = "lowest" ];  then composer update                   --no-progress --no-scripts --no-suggest -n --prefer-lowest; fi;
  - if [ "$dependencies" = "highest" ]; then composer require phpro/grumphp:*  --no-progress --no-scripts --no-suggest -n; fi;

script:
   - ./vendor/bin/grumphp run
